name: Test and Build Flutter

on:
  push:
  pull_request:

permissions: read-all

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.read_fvm_config.outputs.flutter-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Flutter Version
        id: read_fvm_config
        run: |
          FLUTTER_VERSION=$(cat .fvmrc | jq -r '.flutter')
          echo "flutter-version=$FLUTTER_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.read_fvm_config.outputs.flutter-version }}
          cache: true

      - name: Install packages
        run: flutter pub get

      - name: Run build-runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Setup env for tests
        run: cp .env.dev .env

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          verbose: true

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: unit-test
    strategy:
      matrix:
        target: [apk --debug, appbundle --debug]
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.unit-test.outputs.flutter-version }}
          cache: true

      - name: Install packages
        run: flutter pub get

      - name: Run build-runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Configure Keystore
        run: |
          echo "debugStoreFile=keystore/debug_keystore" >> key.properties
          echo "debugKeyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "debugStorePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "debugKeyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          KEYSTORE_KEY_ALIAS: ${{ secrets.DEBUG_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.DEBUG_KEYSTORE_PASSWORD }}
        working-directory: android

      - name: Prepare env file
        run: cp .env.dev .env

      - name: Build ${{ matrix.target }}
        run: flutter build ${{ matrix.target }}

      - name: Upload APK
        if: matrix.target == 'apk --debug'
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7

  ui-test:
    permissions: read-all
    uses: ./.github/workflows/maestro_test.yml
